GLOBAL:
    TIMEZONE: "Europe/Prague"
    LOGFILE: "-"
    PIDFILE: "/tmp/jetconf.pid"
    PERSISTENT_CHANGES: true
    LOG_LEVEL: "debug"
    LOG_DBG_MODULES: ["usr_conf_data_handlers", "knot_api", "nacm", "data","rest_server"]
    DATA_JSON_FILE: "/home/osboxes/jetconf/data/example-data.json"
    YANG_LIB_DIR: "/home/osboxes/jetconf/yang-data/"

HTTP_SERVER:
    DOC_ROOT: "/home/osboxes/jetconf/data/doc-root"
    DOC_DEFAULT_NAME: "index.html"
    API_ROOT: "/restconf"
    SERVER_NAME: "jetconf-h2"

    SERVER_SSL_CERT: "/home/osboxes/jetconf/data/server.crt"
    SERVER_SSL_PRIVKEY: "/home/osboxes/jetconf/data/server.key"
    CA_CERT: "/home/osboxes/jetconf/data/ca.pem"
    DBG_DISABLE_CERTS: false

NACM:
    ALLOWED_USERS: ["lojza@mail.tld"]

KNOT:
    SOCKET: "/home/osboxes/knot-conf/knot.sock"
